// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/agents" | "/admin/construction-projects" | "/admin/inquiries" | "/admin/listings" | "/admin/listings/[id]" | "/admin/listings/new" | "/admin/travel-applications" | "/agent" | "/agent/help" | "/agent/listings/[id]" | "/agent/listings/new" | "/agent/under-review" | "/contact" | "/dashboard" | "/forgot-password" | "/login" | "/privacy" | "/real-estate" | "/real-estate/dashboard" | "/real-estate/properties" | "/real-estate/properties/[propertyId]" | "/register" | "/reset-password" | "/terms" | "/travels" | "/travels/dashboard" | "/travels/dashboard/applications" | "/travels/dashboard/help" | "/travels/dashboard/profile" | "/travels/dashboard/updates"
type AppRouteHandlerRoutes = "/api/payments/agent-onboarding/callback" | "/api/travel-documents/[documentId]" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/agent" | "/real-estate/dashboard" | "/travels/dashboard"
type RedirectRoutes = "/real-estate/properties" | "/real-estate/properties/[[...path]]" | "/travels" | "/travels/[[...path]]"
type RewriteRoutes = "/properties" | "/properties/[[...path]]" | "/travel" | "/travel/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/agents": {}
  "/admin/construction-projects": {}
  "/admin/inquiries": {}
  "/admin/listings": {}
  "/admin/listings/[id]": { "id": string; }
  "/admin/listings/new": {}
  "/admin/travel-applications": {}
  "/agent": {}
  "/agent/help": {}
  "/agent/listings/[id]": { "id": string; }
  "/agent/listings/new": {}
  "/agent/under-review": {}
  "/api/payments/agent-onboarding/callback": {}
  "/api/travel-documents/[documentId]": { "documentId": string; }
  "/auth/callback": {}
  "/contact": {}
  "/dashboard": {}
  "/forgot-password": {}
  "/login": {}
  "/privacy": {}
  "/properties": {}
  "/properties/[[...path]]": { "path"?: string[]; }
  "/real-estate": {}
  "/real-estate/dashboard": {}
  "/real-estate/properties": {}
  "/real-estate/properties/[[...path]]": { "path"?: string[]; }
  "/real-estate/properties/[propertyId]": { "propertyId": string; }
  "/register": {}
  "/reset-password": {}
  "/terms": {}
  "/travel": {}
  "/travel/[[...path]]": { "path"?: string[]; }
  "/travels": {}
  "/travels/[[...path]]": { "path"?: string[]; }
  "/travels/dashboard": {}
  "/travels/dashboard/applications": {}
  "/travels/dashboard/help": {}
  "/travels/dashboard/profile": {}
  "/travels/dashboard/updates": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/agent": never
  "/real-estate/dashboard": never
  "/travels/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
