// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(admin)/admin/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agents">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/construction-projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/construction-projects">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/construction-projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/inquiries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inquiries">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/inquiries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/listings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/listings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/listings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/listings/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/listings/new">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/listings/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/listings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/listings">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/listings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/travel-applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/travel-applications">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/travel-applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/(real-estate)/real-estate/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/real-estate/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/(real-estate)/real-estate/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/(real-estate)/real-estate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/real-estate">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/(real-estate)/real-estate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/(real-estate)/real-estate/properties/[propertyId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/real-estate/properties/[propertyId]">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/(real-estate)/real-estate/properties/[propertyId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/(real-estate)/real-estate/properties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/real-estate/properties">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/(real-estate)/real-estate/properties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/(travel)/travels/dashboard/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/travels/dashboard/applications">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/(travel)/travels/dashboard/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/(travel)/travels/dashboard/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/travels/dashboard/help">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/(travel)/travels/dashboard/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/(travel)/travels/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/travels/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/(travel)/travels/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/(travel)/travels/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/travels/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/(travel)/travels/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/(travel)/travels/dashboard/updates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/travels/dashboard/updates">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/(travel)/travels/dashboard/updates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/(travel)/travels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/travels">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/(travel)/travels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/agent/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/help">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/agent/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/agent/listings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/listings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/agent/listings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/agent/listings/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/listings/new">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/agent/listings/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/agent/under-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/under-review">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/agent/under-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/construction/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/construction/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/construction/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payments/agent-onboarding/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/agent-onboarding/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/payments/agent-onboarding/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(admin)/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/(real-estate)/real-estate/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/real-estate/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/(real-estate)/real-estate/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/(travel)/travels/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/travels/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/(travel)/travels/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/agent/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/agent">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/agent/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/construction/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/construction/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/construction/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(site)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(site)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
